language: node_js
node_js:
- '8'
- stable
- lts/*
os:
- linux
- osx
after_success:
- npm run coverage
deploy:
  provider: npm
  email: sogo@longtail-software.co.jp
  api_key:
    secure: QZld1bQNSxVyM/2AWFlV5nha3aYcLksGKUQT8uBpw02floA7GZ/mphpIJ9bhG8auoycmEWz6FCUm7cH01r1Yhu8ktl+1y8LB6CMR125FC4gX1JdP7Lw9mcRKZLk7YuuUI0B/0Dj38iXNsfoSeJ48+b/d6rYVOG3N/HnP9lfRL3rXTkPWBtdMvKRVqem7Ujm97YfrlAHYMBqwPYfeVYEbiH8CGacfCP3fRDFDTuBakABpZN3WiY+/JwIqQxX6NsSXUnoC/DWKyz832KfgZCTqJrig6PvKo+LEPm2jIHu3R3W1DVixteriv8OsLAVpHOxhAaEHQWY89aZ1Fa6nXrY4ocIUe9VXh+XAE2ey+sYFuNWzcPLPPs34QUwlkh3ql3Zfzy+VohnQfLjFoDwFFSBPpPi4/ODkqEWxCxuBJYZcBkDNPY8BBuh0Y/Aaxo2y4nVyDiCvc3z6DzGyoRWBI7FDprsKn3JsHhuSxr90MGRqON78uEBHc43sVYb00sucQUJagCJZK9rvd/hUaS7Di95DdfrfxeS2qttMr6aFqI7MXp7EjrG4oMXJ+BCFLjRI0bzrKMz53PNcZJhmU3xCnQuoE6gE0xHzF6xinuqyekGJeHdcQCEzOIBFwpptexqYm9n6rbJKLCmHQy7rwh2v9wCbAIdT/QrhdqjLi2W9BBcSpQY=
  on:
    tags: true
  skip_cleanup: true
notifications:
  mail: false
  slack:
    secure: DbKATt/jcvIMJ4o3LxULNJEMmWLBVYdrGYkCSpENf4HaFP/R5rP8dZRhPYNFBL8203k0ZrXOytS9Z/lhz7mPKqxWgIAH0hvF+IewEwEDM1VMulSHeBRN9GeRAJFTBCtKtElXPtvg2hjLQzoygXY87Gs4D0C524tgCk1jPiZhRSMgQ08cXMfpgLDEM/pynyiOBOEyOz5badJlttv9KLQnUMOxS/lE+JllBjPCoVo7rX00NKOIUhhLQWU7VMn6gDtIQZtx8VFRRd5bBID6L+8dA8LCVt28Wss6BbCYU8jthd/RmV1JPalx5+TNx8gmGMcQOB2cBc4Omke0rSX6EtbPfjql5L0xw7fuN4zKlGP35HFdClCQ6zGZisJ6Ef9wwX0t0BUtbHiABVb+7TPRIyOKddMeC0qhvrtAkAYmDU54BqzZ0MGMhr9J2mx2OeDe9WY0Vvve9kMIYCbQqLy+FRF6kaQU5k46GXreEDX0UGuiKi0SSTKx7TSOrJjVSL2rFD7uE3Te3F9l5vE9NTEIGlWWJ4BvpPVYDUhcamsUeqA3sJiQ5x5OimsRdotvdRvm4NV3TwWTRSSSWt8OP5+86ZcOeeJxj2kiYMRFtoVz052J+HbeKo2FJ/kIX/0M1iIqiX/ZpJc8DaL7bel9ZHg+fsHoYb/uKQXcBp5/z2+4QgCvzCI=
