language: node_js
node_js:
- '8'
- stable
- lts/*
os:
- linux
- osx
after_success:
- npm run coverage
deploy:
  provider: npm
  email: sogo@longtail-software.co.jp
  api_key:
    secure: QZld1bQNSxVyM/2AWFlV5nha3aYcLksGKUQT8uBpw02floA7GZ/mphpIJ9bhG8auoycmEWz6FCUm7cH01r1Yhu8ktl+1y8LB6CMR125FC4gX1JdP7Lw9mcRKZLk7YuuUI0B/0Dj38iXNsfoSeJ48+b/d6rYVOG3N/HnP9lfRL3rXTkPWBtdMvKRVqem7Ujm97YfrlAHYMBqwPYfeVYEbiH8CGacfCP3fRDFDTuBakABpZN3WiY+/JwIqQxX6NsSXUnoC/DWKyz832KfgZCTqJrig6PvKo+LEPm2jIHu3R3W1DVixteriv8OsLAVpHOxhAaEHQWY89aZ1Fa6nXrY4ocIUe9VXh+XAE2ey+sYFuNWzcPLPPs34QUwlkh3ql3Zfzy+VohnQfLjFoDwFFSBPpPi4/ODkqEWxCxuBJYZcBkDNPY8BBuh0Y/Aaxo2y4nVyDiCvc3z6DzGyoRWBI7FDprsKn3JsHhuSxr90MGRqON78uEBHc43sVYb00sucQUJagCJZK9rvd/hUaS7Di95DdfrfxeS2qttMr6aFqI7MXp7EjrG4oMXJ+BCFLjRI0bzrKMz53PNcZJhmU3xCnQuoE6gE0xHzF6xinuqyekGJeHdcQCEzOIBFwpptexqYm9n6rbJKLCmHQy7rwh2v9wCbAIdT/QrhdqjLi2W9BBcSpQY=
  on:
    tags: true
  skip_cleanup: true
notifications:
  mail: false
  slack:
    secure: dw5pTcP0FwtoCsEi0FC5m6/gSxA/yueUj2iNQ/y6DYqx0peXLJjJiMvW+HyWNrvgx85aObszDhBD4HnR05ENo1+0p8UWUqHmgjsRbZWUc4yrftGMa7OW8CC6gmKakPYyyukS1S4r1P0PYG1mUCUTkhz+e9/fI3od2FA1tH5+p94OFO74+u0Ppq4/bwrCzRzwhscrP1KPVuD+6p5vmZ+p37ZU6aapUv+MJujtN4qdDUos2GUjONc6JS/mm+gQ2T/WC7UbQe4aFSQsv42VH/HBDedDS83Qvqa0c2hrBmpLQFDNJ8e2Wc1997OKclkfDYJWzcV+ah1eOtlj1iX2NPIkHi5hq5lOAeUr4pgtoK+yIjuBUH9Uy9Xr9Pll6h0bIdU+/vCe61FTBAfKdZGuclUhmZJih7vZP481B3OoreDV4e0CU/NtguwkyiJsYNQ8/L0/oXx/5BxMjl9MW0EJ9h1oiUiBnKk3B83W5k0rVg7mZj06WHG9kL9bgRjCGl/733msTODPR1nEV7aNUdTos09iNRciu6p5Cc/vdi9/RvEvQSPVbWiX9Qvb6I4b7ryWgir1JSVf29BI3nOvk1L1kA8/cXwghGHNYSp+bjXgVOC+XuA/kbfi+n4KkAIN1/yJS7qhfl0V8At0quAtJ9QeV39gQOn1drV+vCuS+2qpSeOn57E=
