language: node_js
node_js:
- '8'
- stable
- lts/*
os:
- linux
- osx
jobs:
  include:
  - stage: cross-platform test
    script: npm run test
  - stage: full test and publish to npm
    node_js: lts/*
    os: linux
    script: npm run test
    env: ABC4_FULLTEST=YES
    after_success: npm run coverage
    deploy:
      provider: npm
      email: sogo@longtail-software.co.jp
      api_key:
        secure: QZld1bQNSxVyM/2AWFlV5nha3aYcLksGKUQT8uBpw02floA7GZ/mphpIJ9bhG8auoycmEWz6FCUm7cH01r1Yhu8ktl+1y8LB6CMR125FC4gX1JdP7Lw9mcRKZLk7YuuUI0B/0Dj38iXNsfoSeJ48+b/d6rYVOG3N/HnP9lfRL3rXTkPWBtdMvKRVqem7Ujm97YfrlAHYMBqwPYfeVYEbiH8CGacfCP3fRDFDTuBakABpZN3WiY+/JwIqQxX6NsSXUnoC/DWKyz832KfgZCTqJrig6PvKo+LEPm2jIHu3R3W1DVixteriv8OsLAVpHOxhAaEHQWY89aZ1Fa6nXrY4ocIUe9VXh+XAE2ey+sYFuNWzcPLPPs34QUwlkh3ql3Zfzy+VohnQfLjFoDwFFSBPpPi4/ODkqEWxCxuBJYZcBkDNPY8BBuh0Y/Aaxo2y4nVyDiCvc3z6DzGyoRWBI7FDprsKn3JsHhuSxr90MGRqON78uEBHc43sVYb00sucQUJagCJZK9rvd/hUaS7Di95DdfrfxeS2qttMr6aFqI7MXp7EjrG4oMXJ+BCFLjRI0bzrKMz53PNcZJhmU3xCnQuoE6gE0xHzF6xinuqyekGJeHdcQCEzOIBFwpptexqYm9n6rbJKLCmHQy7rwh2v9wCbAIdT/QrhdqjLi2W9BBcSpQY=
      on:
        tags: true
      skip_cleanup: true
notifications:
  mail: false
  slack:
    secure: VHnlm8pP8WfX528MzRZVAIZLOODtRFEAV4U7G1L56hbYtJt8toy6ZmkX11wBO6r2JuEQ6xOfsDNdoBoq9TMLTtE0OBOKfkIrKJ1pT1DQwj69AmUat4tpNI5SrXNCypCxKHKLV+SRhzmqys1C+De4RoSIC4IZt3tQiiFrnwSrgTaKXARKO57erl5wI10BOSyoLpMkua5/+OTQCJRKJ9bo0j71118C+ivr4KOcJ7WWfjNpkHYRlRlWz5UIzej0x4YQGqH8YoiD/Sd8gVgMXRLjcPj5mG1m4t/jLMXDckqyPtaCfWtxcQKF1+9XxYSvWG9Wsop7Ole/m5CIWDNs/XzdtTq08b/7+wSke+3yzegflgpW9tL1QfnMB24QsI4eFQwikzFrlSuwl2B9vvrDY2LgxDeLME038zugo7cQbpsm2atg7tXd01HnrIbt+dhUvXujIRJ6Nz9WtmhkgXxixP4rY9whK/A1e/5iacEm78KAeodAlHpLXHPRJKRBJNy5gKtika1y6CMl2r/PYJrP9SiyeInPeSoYEEoLaE1Aun1e+qrK8lrKMkN9xV8Rd9GEUZ7WMBjGtcCmdkAop5jkzviZlsTA/y7XID/c3qpxG9OItkZ+5c2sDHi/ezY3ILhB+KEov+3vTAP4+A2M/DuAGBGCMnDnn9S7bFtjp88rDobGf6w=
